### ISSUE TITLE
Craft 5 support

### ISSUE THREAD

**Issue by CreateSean** [dodecastudio/craft-feedreader#2]
Do you have plans to update this plugin for Craft 5?

**Comment by tomkiss** [comment]
Hi Sean,
Yes I would like to, just need to find the time!

**Comment by CreateSean** [comment]
Excellent. Looking forward to it when you find the time. Thank you for the update.

**Comment by tomkiss** [comment]
Hi @CreateSean,

I've just pushed out a new version that supports Craft 5. Tested in Craft 3, 4 and 5 but let me know if you see any issues.

Thanks!

https://github.com/dodecastudio/craft-feedreader/releases/tag/v2.0.0
